#pragma config(Sensor, S1,     gyro,           sensorEV3_Gyro)
#pragma config(Sensor, S2,     ColorRight,     sensorEV3_Color)
#pragma config(Sensor, S3,     ColorLeft,      sensorEV3_Color)
#pragma config(Sensor, S4,     ultra,          sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          hand,          tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorB,          left,          tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          right,         tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "AlgorithmTypeFunctions.c"

int handSpd = 30; // Speed A Hand Is Moving With.

int handTarget;
//handTarget Is An int Type Variable Showing The Current Target The Hand Is Moved To.
//This Task Is Used to Move Hand To Given Destination.
task setHand() {
	int currTime;

	while(true) {
		if(getMotorTarget(hand) != handTarget)
				setMotorTarget(hand, handTarget, handSpd);

		currTime = time1[T1];
		while(timer_count(currTime, time1[T1]) <= 10){}

	}
}

void moveHand(int setPoint){

	handTarget = setPoint;

	stopTask(setHand);

	startTask(setHand);
}

task main() {

}
