#pragma config(Sensor, S1,     color1,         sensorEV3_Color)
#pragma config(Sensor, S2,     gyro,           sensorEV3_Gyro)
#pragma config(Motor,  motorB,          wheelL,        tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          wheelR,        tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "AlgorithmTypeFunctions.c"
#include "PID.c"
#include "PID_tasks.c"
#include "PID_tasks_StartAndStop.c"
#include "PID_functions.c"

PID lineFollower_slow;

task main()
{
	PID_init(&lineFollower_slow, 0.3, 0.00023, 0.239, 18.3, 80, -80, 30, 20);

	PID_LineFollower_Start(lineFollower_slow);
}
