#pragma config(Sensor, S1,     usonic,         sensorEV3_Ultrasonic)
#pragma config(Sensor, S2,     gyro,           sensorEV3_Gyro)
#pragma config(Sensor, S3,     color2,         sensorEV3_Color)
#pragma config(Sensor, S4,     color1,         sensorEV3_Color)
#pragma config(Motor,  motorA,          claw,          tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorB,          wheelR,        tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorC,          wheelL,        tmotorEV3_Medium, PIDControl, reversed, encoder)
#pragma config(Motor,  motorD,          hand,          tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// color1 - LineFollower-is Sensor-i
// color2 - ColorCheck-is Sensor-i

//float lineCorrectionTime = 1000;

#include "AlgorithmTypeFunctions.c"
#include "PID.c"
#include "PID_Usage.c"
#include "PID_tasks.c"
#include "PID_Start.c"
#include "PID_LineFollower.c"
#include "PID_Gyro.c"
#include "PID_Hand&Claw.c"
#include "Functions.c"
#include "PID_highLevelFunctions.c"
#include "Initialization.c"


PID LineFollower_normal_r;
PID LineFollower_normal_l;
PID Gyro_rotate;
PID Hand_normal;
PID Claw_normal;
PID Gyro_mover;
task main()
{
	Initializate();

	PID_init(&LineFollower_normal_r, 0.5, 0.02, 0.0009, 0.000666666, 80, -80, 37, 30);
	PID_init(&LineFollower_normal_l, 0.5, 0.02, 0.0009, 0.000666666, 80, -80, 52, 30);
	PID_init(&Gyro_rotate, 1.5, 0.001, 0, 0.000666666, 80, -80, 45, 15);
	PID_init(&Gyro_mover, 0.1, 0.02, 0.0009, 0.000666666, 80, -80, 52, 5);
	PID_init(&Hand_normal, 1, 0.09, 0.023, 0.00043, 80, -80, 0, 0);
	PID_init(&Claw_normal, 3, 0.0, 0.0, 0.00043, 80, -80, 0, 0);

	PID_Hand_Start(Hand_normal, on_always, 0);
	LineFollower_normal_r.lineCorrectionTime = 1500;
	LineFollower_normal_l.lineCorrectionTime = 1500;

	Gyro_rotate.oneSided = false;
	Gyro_rotate.side = true;
	Gyro_mover.oneSided = false;

	PID_FollowLine_AndTurn(LineFollower_normal_r, Gyro_rotate, 15, -90, 1, 2);
	while(1)
	{
	}

}
