#pragma config(Sensor, S1,     color1,         sensorEV3_Color)
#pragma config(Sensor, S2,     gyro,           sensorEV3_Gyro)
#pragma config(Sensor, S3,     color2,         sensorEV3_Color, modeEV3Color_Ambient)
#pragma config(Sensor, S4,     usonic,         sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          hand,          tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorB,          wheelR,        tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          wheelL,        tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorD,          claw,          tmotorEV3_Medium, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// color1 - LineFollower-is Senro-i
// color2 - ColorCheck-is Sensor-i

// Debug-is Mosadzebni Kodi -> TEMPORARY_FOR_DEBUGGING

#include "AlgorithmTypeFunctions.c"
#include "PID.c"
#include "PID_tasks.c"
#include "PID_tasks_StartAndStop.c"
#include "PID_functions.c"
#include "Functions.c"

task main()
{
}
