#pragma config(Sensor, S1,     usonic,         sensorEV3_Ultrasonic)
#pragma config(Sensor, S2,     gyro,           sensorEV3_Gyro)
#pragma config(Sensor, S3,     color2,         sensorEV3_Color)
#pragma config(Sensor, S4,     color1,         sensorEV3_Color)
#pragma config(Motor,  motorA,          claw,          tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorB,          wheelR,        tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorC,          wheelL,        tmotorEV3_Medium, PIDControl, reversed, encoder)
#pragma config(Motor,  motorD,          hand,          tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// color1 - LineFollower-is Sensor-i
// color2 - ColorCheck-is Sensor-i

//float lineCorrectionTime = 1000;

int AAAA;

int cBlack = 8;
int cDarkBlue = 11;
int cBlue = 15;
int cWhite = 76;

int badCol[2];

int checkedColor = -1;
bool checkStatus = false;

int colorsAsked[2]  ={2, 2}; 					// 3=Mwvane, 2=Blue, 0=Empty.
int blockColors[4] = {0, 0, 0, 0}; 		// 3=Mwvane, 2=Blue, 0=Empty.
int goodBlocks[2] = {0, 0};
int badBlocks[1] = {0};
int robotBlocks[4] = {0, 0, 3, 3};		// 3=Mwvane, 2=Blue, 0=Empty.

#include "AlgorithmTypeFunctions.c"
#include "PID.c"

PID Hand_normal;
PID LineFollower_sonic_r;
PID LineFollower_sonic_l;
PID LineFollower_fast_r;
PID LineFollower_fast_l;
PID LineFollower_normal_r;
PID LineFollower_normal_l;
PID LineFollower_ship_l;
PID LineFollower_slow_l;
PID LineFollower_slow_r;
PID Gyro_rotate;
PID Gyro_move;
PID Gyro_move_fast;
PID Encoder_move;
PID Encoder_move_fast;
PID Encoder_rotate;

#include "PID_Usage.c"
#include "PID_tasks.c"
#include "PID_Start.c"
#include "PID_LineFollower.c"
#include "PID_Gyro.c"
#include "PID_Hand&Claw.c"
#include "Hand&Claw.c"
#include "PID_Encoder.c"
#include "Functions.c"
#include "Tasks.c"
#include "PID_highLevelFunctions.c"
#include "Initialization.c"
#include "DoTheJob_1.c"
#include "DoTheJob_2.c"
#include "DoTheJob_3.c"
#include "DoTheJob_4.c"
#include "DoTheJob_5.c"
#include "DoTheJob_6.c"

task main()
{
	Initializate();

	LineFollower_sonic_l.lineCorrectionTime = 3000;
	PID_FollowLine_Until_Reflected(LineFollower_sonic_l, cBlack + 1);
}
